Repository bianjieai/iritamod, pull requests merged in 2021-01, with the labels that each got.

#18 Update cosmos-sdk version
  go.mod
  go.sum
  modules/admin/client/cli/query.go
  modules/admin/client/cli/tx.go
  modules/identity/client/cli/query.go
  modules/identity/client/cli/tx.go
  modules/node/client/cli/query.go
  modules/node/client/cli/tx.go
  modules/node/genesis.go
  modules/node/keeper/historical_info.go
  modules/node/keeper/keeper_test.go
  modules/node/keeper/validator.go
  modules/node/keeper/validator_update.go
  modules/node/types/validator.go
  modules/params/client/cli/tx.go
  modules/slashing/client/cli/tx.go
  modules/upgrade/client/cli/tx.go
  simapp/app.go
  simapp/test_helpers.go
Labels: build

#20 Update comsos-sdk to v0.40.0
  go.mod
  go.sum
  modules/identity/types/msgs_test.go
  modules/identity/types/utils.go
  modules/node/keeper/historical_info.go
  modules/node/keeper/validator.go
  simapp/test_helpers.go
  utils/ca/cert.go
  utils/ca/sm2_cert.go
Labels: automerge

#22 Add MintAdmin role
  modules/admin/alias.go
  modules/admin/client/cli/tx.go
  modules/admin/types/admin.pb.go
  modules/admin/types/auth.go
  modules/admin/types/role.go
  proto/admin/admin.proto
Labels: enhancement
